### ISSUE TITLE
Couldn't parse example for `load_race_session()` and `load_driver_telemetry()`

### ISSUE THREAD

**Issue by SCasanova** [SCasanova/f1dataR#100]
Got the following warning when building the site

`1: Failed to parse example for topic 'load_driver_telemetry' 
2: Failed to parse example for topic 'load_race_session' `

**Comment by pbulsink** [comment]
Hangover from #95, I'll try sort those out.

**Comment by pbulsink** [comment]
Those are both hidden in \dontrun{} tags because of their runtime (CRAN wants < 5 s for total examples running). 

Does the warning prevent building of the site?

**Comment by SCasanova** [comment]
Ah ok makes sense
