### ISSUE TITLE
Format R code to standard

### ISSUE THREAD

**Issue by pbulsink** [SCasanova/f1dataR#113]
Consider formatting R code with `formatR`, `styler` and/or `lintr`- could do automatically at merge with a Github action.

@SCasanova feel free to assign to me if you think it's a good idea, or close if you'd rather not do that.

**Comment by SCasanova** [comment]
I like it. From a quick look at the options `styler` (+ `lintr`) might be the best choice (?). Do you have a preference?

**Comment by pbulsink** [comment]
I've done some work with lintr so styler is a better match (they are from
the same dev).

Lintr is very picky so it'll help with general code quality and
consistency.

**Comment by SCasanova** [comment]
Sounds good to me. Also, I'm back to the same timezone so that will be nice for collaborating

**Comment by pbulsink** [comment]
I need to validate that styler code is running on PR before closing this.

**Comment by pbulsink** [comment]
In working with #126 I had a commit added by the styler job ( I think) so that's likely working.
