### ISSUE TITLE
Workflow to build Pkgdown doesn't push to github pages

### ISSUE THREAD

**Issue by pbulsink** [SCasanova/f1dataR#124]
#120 doesn't look like it pushed all the way to the github pages.

_Originally posted by @pbulsink in https://github.com/SCasanova/f1dataR/issues/120#issuecomment-1631632304_

**Comment by SCasanova** [comment]
Yeah odd. I see the workflow as completed but no changes

**Comment by pbulsink** [comment]
I'll have to do some checking if the workflow action to make sure it lines up properly with how the repo is configured. Looks like it prepped all the files but just couldn't deploy. 
![Screenshot_20230712-070144](https://github.com/SCasanova/f1dataR/assets/5419974/f4a6276e-4430-4458-97fd-d64a0a203bb9)

**Comment by pbulsink** [comment]
Possibly handled by #125 ?

**Comment by pbulsink** [comment]
The PR checks fail on the pkgdown build job (makes sense, as we shouldn't update the docs until after a merge). With #126 we can see if it properly updates *after* merge is accepted.

**Comment by pbulsink** [comment]
No update after #126

**Comment by pbulsink** [comment]
Also (possibly related) style fails on push changes...

**Comment by pbulsink** [comment]
Works now? https://github.com/SCasanova/f1dataR/commit/9524a52ede7e549e5e7efbdadcb10a2ffb38f61b

**Comment by pbulsink** [comment]
Seems to be ok - failed after some missed topics but most recent is good.
