### ISSUE TITLE
Reach out to Ergast

### ISSUE THREAD

**Issue by pbulsink** [SCasanova/f1dataR#130]
Ergast has a list of (mostly python) tools that folks can use to access their data/api.

http://ergast.com/mrd/development-tools/

Maybe @SCasanova could reach out to them after CRAN submission and a) let them know of our project for them to share on their site (likely via CRAN - `install.package('f1dataR')`) and b) that our hits to their db using our package will have a 'f1dataR/X.X.X' useragent (with the version number for X.X.X).

**Comment by SCasanova** [comment]
Will do

**Comment by SCasanova** [comment]
I have reached out, awaiting response

**Comment by pbulsink** [comment]
Should we let FastF1 know too?

**Comment by SCasanova** [comment]
Could be a good idea

**Comment by SCasanova** [comment]
There seems to be no set way to contact the dev for stuff like this. Also no response from Ergast yet

**Comment by pbulsink** [comment]
Notified them in a discussion (not really an issue to solve) https://github.com/theOehrly/Fast-F1/discussions/437
