### ISSUE TITLE
Finish CRAN submission

### ISSUE THREAD

**Issue by pbulsink** [SCasanova/f1dataR#136]
I think it's ready for CRAN submission! 

Close Issues #37, #38, #39, #59, merge PR #134, #135. 

Unless you think #78 or #123 are outstanding?

**Comment by SCasanova** [comment]
I do think #123 is important but I think  I cracked it yesterday (I want your opinion on my solution)

However as it's not a perfect solution I do think it could remain as a part of the "dev" version post-CRAN

**Comment by SCasanova** [comment]
Other than that I think we're ready to submit

**Comment by SCasanova** [comment]
Sorry, I've been very busy. Will push later today

**Comment by SCasanova** [comment]
On second thought, I think it needs more work. We should go ahead without it for now.

**Comment by pbulsink** [comment]
Feel free to open a PR from a dev branch and we can collaborate on it, and
use master for the cran submission while we wait?

**Comment by SCasanova** [comment]
Sounds good. Should I get the submission going then?

**Comment by pbulsink** [comment]
I'd say go for it! I've never submitted anything to CRAN before, but I
think `devtools` or `usethis` has a helper function to prep whatever files
are needed and help through the process.
