### ISSUE TITLE
Move to httr2

### ISSUE THREAD

**Issue by pbulsink** [SCasanova/f1dataR#153]
`httr2` allows for simple retry, rate limits, and better test interfaces - maybe migrate to build in ergast auto-retries & prevent hitting their server too hard during testing

**Comment by pbulsink** [comment]
Could relate to #152 `interactive()` calls

**Comment by SCasanova** [comment]
Wouldn't that still exceed 5s test time?

**Comment by pbulsink** [comment]
Yes, but can we request exceptions for API type delays?

**Comment by SCasanova** [comment]
Closed by #155
