### ISSUE TITLE
Update Docs per CRAN

### ISSUE THREAD

**Issue by pbulsink** [SCasanova/f1dataR#156]
- [x] Please add a web reference for the API in the form <https:.....> to the description of the DESCRIPTION file with no space after 'https:' and angle brackets for auto-linking.

- [x] Please add \value to .Rd files regarding exported methods and explain the functions results in the documentation. Please write about the structure of the output (class) and also what the output means. (If a function does not return a value, please document that too, e.g. \value{No return value, called for side effects} or similar)

Missing Rd-tags:
- [x] clear_f1_cache.Rd:  \value
- [x] setup_fastf1.Rd: \value

**Comment by SCasanova** [comment]
Closed by #158
