### ISSUE TITLE
Style fails on push changes

### ISSUE THREAD

**Issue by SCasanova** [SCasanova/f1dataR#159]
Also (possibly related) style fails on push changes...

_Originally posted by @pbulsink in https://github.com/SCasanova/f1dataR/issues/124#issuecomment-1673435282_

**Comment by pbulsink** [comment]
Yeah I think #124 and this have the same root cause - permissions on push. Not sure I can solve it as easily as you since I don't have repo write permission, but I plan to do more reading up on this anyway

**Comment by SCasanova** [comment]
What do I need to do?

**Comment by pbulsink** [comment]
I'm not sure yet, i'll get back to you once I understand the nitty gritty of github actions a bit better.

**Comment by pbulsink** [comment]
From docs on some workflow actions:

For this action to work you must explicitly allow GitHub Actions to create pull requests. This setting can be found in a repository's settings under Actions > General > Workflow permissions.

@SCasanova I can't make that change, if you do it before you merge #171 then we'll see if it fails the auto-doc/auto-style (it might not as I think there's no changes anyway?)

**Comment by SCasanova** [comment]
Hmm I checked and that looks to be already on. I also made you a collaborator (which should've been done a long time ago). I don't know if that allows you to modify that as well

**Comment by SCasanova** [comment]
Fantastic
