### ISSUE TITLE
Update NEWS with changes since CRAN

### ISSUE THREAD

**Issue by pbulsink** [SCasanova/f1dataR#184]
Mostly just for me to keep track of, but we should keep news up to date with changes since last CRAN push to help guide us when to do an update there.

**Comment by pbulsink** [comment]
@SCasanova what would you suggest is 'big enough' for releasing 1.3.1 to send to CRAN? Our cache management seems better than 1.3.0, but I'm not sure how CRAN feels about minor patch updates.

**Comment by SCasanova** [comment]
Hmm I'm not sure. I will dive into their documents to check if they have a recommendation otherwise it's just a matter of it greatly improves the overall experience. In this case I think it could be warranted

**Comment by pbulsink** [comment]
I think now we can do a CRAN push.
