### ISSUE TITLE
GH Actions R CMD Chk Failures

### ISSUE THREAD

**Issue by pbulsink** [SCasanova/f1dataR#187]
Recently CMD Chk fails on PR/Push for ubuntu tasks. Even previously passing checks fail.

**Comment by pbulsink** [comment]
https://github.com/SCasanova/f1dataR/actions/runs/6217170530/job/16871925042#step:8:216

**Comment by pbulsink** [comment]
#189 didn't work. I might wait a week, I think the issue is with 'reticulate' so I'll wait for more bug reports to pop up and a fix to roll out to GH Actions

**Comment by SCasanova** [comment]
Do we know anything about this?

**Comment by pbulsink** [comment]
Not yet. I'll do more research but I worry we'll have to remove the affected function(s) and  just provide the advice vignette and a link to reticulate documentation.

I don't want CRAN checks to end up with the same issue blocking a bugfix release in the future.

**Comment by SCasanova** [comment]
Damn yeah makes sense

**Comment by pbulsink** [comment]
So I rechecked the `reticulate` documentation.
 [Here](https://rstudio.github.io/reticulate/articles/package.html) they briefly, but essentially suggest that we offer a convenience function that wraps `reticulate` to install the python package we need (i.e. `fastf1`). Why don't we do that instead of all of the virtualenv stuff? They suggest (wisely) that a user may wish to have multiple `reticulate` based packages active at once in one virtualenv, this approach simplifies that possibility.

**Comment by SCasanova** [comment]
Yes that makes perfect sense and is more user friendly too
