### ISSUE TITLE
Ergast is shutting down

### ISSUE THREAD

**Issue by SCasanova** [SCasanova/f1dataR#193]
> The Ergast API is now DEPRECATED
> 
> The API will be updated until the end of the 2024 season then shutdown at the end of the year.

This is now posted on the Ergast home page. We should look to find alternatives for that type of info / maybe even capture historical data before the shutdown

**Comment by pbulsink** [comment]
Ergast enables downloads of the whole database in various formats (.csv files, some sort of sql file, etc.). This may be an option. We'll watch and see what FastF1 does too.

**Comment by pbulsink** [comment]
Update: FastF1 is on it, looking at a few different options: https://github.com/theOehrly/Fast-F1/discussions/445
