### ISSUE TITLE
Difficulty loading some functions

### ISSUE THREAD

**Issue by pbulsink** [SCasanova/f1dataR#199]
### Discussed in https://github.com/SCasanova/f1dataR/discussions/197

<div type='discussions-op-text'>

<sup>Originally posted by **saimingliew** November  7, 2023</sup>
Thanks for creating this package! I'm having trouble with some of the functions. For example, when I write:
```r
load_driver_telemetry(season = "current", round = "last", session = "R", driver = "VER")
``` 
I get: 
```
Error in if (getOption("f1dataR.cache") %in% c("memory", "off", "filesystem")) { : 
  argument is of length zero
```
Any idea how to fix this?</div>

**Comment by SCasanova** [comment]
Should be fixed in newest dev version. Please download and let me know if that works. 

ps. @pbulsink I fixed a bug on telemetry for new/old fastf1 but I broke the old fastf1 tests in the process

**Comment by pbulsink** [comment]
Per @SCasanova should be closed, if not we can reopen.
