### ISSUE TITLE
Make load_pitstops available for 2011

### ISSUE THREAD

**Issue by christianlohr9** [SCasanova/f1dataR#2]
Me again 😛 

iirc pit stops have been tracked since the 2011 season. 
Atm the function disables everything before 2012.

For example round 1 in 2011:
http://ergast.com/api/f1/2011/1/pitstops.json?limit=80

Thx!
Christian

**Comment by SCasanova** [comment]
You're right. Ergast documentation says it's available starting in 2012 but even their own examples use 2011. I'll get that fixed tomorrow probably.
