### ISSUE TITLE
Fix oldfastf1 test failures

### ISSUE THREAD

**Issue by pbulsink** [SCasanova/f1dataR#200]
In advance of gracefully deprecating fastf1 < 3.1 (#198), these should still work in the meantime. See build failure at https://github.com/SCasanova/f1dataR/commit/cbc0ebb63341084f753775f734880c7693c5ca7a

**Comment by SCasanova** [comment]
Yeah that's my fault. I inverted the version check to generate telemetry but couldn't figure out how to fix the tests
