### ISSUE TITLE
Prep for v1.4.1 to Cran

### ISSUE THREAD

**Issue by pbulsink** [SCasanova/f1dataR#204]
Prep for v1.4.1 to CRAN

- [x] Update version in DESCRIPTION
- [x] Update NEWS.md
- [x] Ensure Github Actions Build Correctly
- [x] Build Docs
- [x] check winrel
- [x] check win_oldrel
- [x] check win_devrel
- [x] check macrel
- [x] check rhub
- [x] Confirm #199 is closed
- [x] submit to CRAN
- [x] build GitHub release
- [x] update to dev version in Github

**Comment by pbulsink** [comment]
First winrel check failed - bad tar file.

**Comment by pbulsink** [comment]
Unless we need code changes for #199, we're good to go with a cran bugfix push, @SCasanova

**Comment by SCasanova** [comment]
nope, should be fixed already. Will submit

**Comment by pbulsink** [comment]
CRAN had 1.4.1 this evening, so I bumped #master to dev after building a release, so we're all set! Thanks.
