### ISSUE TITLE
Package Tests+

### ISSUE THREAD

**Issue by pbulsink** [SCasanova/f1dataR#21]
Hi @SCasanova 

I might add some tests for various package functions to verify that any changes being suggested don't break anything. Unfortunately, Ergast seems to be down at this time, but i'll get the tests written and posted once Ergast is back up and running. 

Once I get them added, would you be interested/able to add CI to run package tests for pull requests and also Code Coverage reports? Let me know if you want a hand with setting that up.

Thanks for a great package!

**Comment by pbulsink** [comment]
#23 closes when merged

**Comment by SCasanova** [comment]
closed by #23
