### ISSUE TITLE
Automated Build Failure

### ISSUE THREAD

**Issue by pbulsink** [SCasanova/f1dataR#224]
Build Failure on the weekly check - https://github.com/SCasanova/f1dataR/actions/runs/7953526995

Seems to be failure in setup of the reticulate venv, not in our code?

**Comment by pbulsink** [comment]
See https://stat.ethz.ch/pipermail/r-devel/2023-July/082722.html for what's likely a related fact. Could be buried in a different package blocking renv build

**Comment by SCasanova** [comment]
Yeah I think that may be it. I'm ok with merging with that fail for now

**Comment by pbulsink** [comment]
I've raised a issue: https://github.com/rstudio/reticulate/issues/1544

**Comment by SCasanova** [comment]
Awesome, thanks

**Comment by pbulsink** [comment]
Per the advice at the issue I raised there #1544, I confirmed that running the Github Actions with dev reticulate allows everything to proceed correctly. Since this isn't our issue, I'm content to leave it as-is and we'll (hopefully) start seeing 100% passing builds again once they update CRAN.

**Comment by SCasanova** [comment]
Thanks for taking care of this. Great job

**Comment by pbulsink** [comment]
The build passes all tests (including future/now current R 4.4.0) successfully, so this is now closed (despite the `reticulate` issue still being open).
