### ISSUE TITLE
CRAN (and weekly build check) Failures

### ISSUE THREAD

**Issue by pbulsink** [SCasanova/f1dataR#228]
Per email from CRAN, also found here: https://github.com/SCasanova/f1dataR/actions/runs/8134930400

**Comment by pbulsink** [comment]
With #229 we should be more stable to Ergast changes, but should still enable testing against failed internet connection.

**Comment by pbulsink** [comment]
#233 ready for review. Once done, we'll need to do a bugfix X.X.1 version bump (no change in user functionality) and push to CRAN before the deadline next week.

**Comment by SCasanova** [comment]
Can you recompile vignettes with dpi = 250 instead of 300, please @pbulsink? We're over the limit on CRAN and for the life of me I can't get optipng to work properly on my machine

**Comment by pbulsink** [comment]
Will do tonight. Want me to do #227 also?

**Comment by SCasanova** [comment]
Thanks for #227, please ignore #241, i made a mess In that branch

**Comment by pbulsink** [comment]
Closed by #237
