### ISSUE TITLE
Pkgdown update

### ISSUE THREAD

**Issue by SCasanova** [SCasanova/f1dataR#239]
Is the action to update pkgdown working? I'm not sure how it works but it seems it's still on 1.3. Could you direct me to the right place @pbulsink

**Comment by pbulsink** [comment]
Good Catch. I looked and saw the warning at the bottom of the run here: https://github.com/SCasanova/f1dataR/actions/runs/8226091186. I can find a new pkgdown action and swap it in.

**Comment by SCasanova** [comment]
Thanks!

**Comment by pbulsink** [comment]
@SCasanova - so pkgdown builds correctly now, but I think the github pages build job pulls from the wrong branch... 

This is unfortunately something that's set in your *personal* gh settings, so you may be able to sort it out with a bit of digging. I saw this that might help https://stackoverflow.com/a/76960283/3933405. Try set the Github Pages setting to build from the `gh-pages` branch?

Alternatively, we can modify the pkgdown build job to push to `master` but that's a bit messier.

**Comment by SCasanova** [comment]
Hmmm I see. I will dig. Thanks

**Comment by pbulsink** [comment]
I found this when looking for a different repo. https://fanwangecon.github.io/PkgTestR/articles/ffv_pkgdown_github.html You might have some success with rerunning the following two functions and allowing it to overwrite the .yml files:

```
usethis::use_github_action("pkgdown")

usethis::use_pkgdown_github_pages()
```

**Comment by SCasanova** [comment]
Should be working properly now
