### ISSUE TITLE
compare results between season 1950-2024

### ISSUE THREAD

**Issue by factorialmap** [SCasanova/f1dataR#247]
In the original structure of the results table, it has a column called `race_id` that made it possible to compare different seasons.

Is there any way to return data with the range from 1950 to the current date?

![image](https://github.com/SCasanova/f1dataR/assets/46722179/4c1d041d-832e-42d6-a217-aaa3618b6f8a)

**Comment by pbulsink** [comment]
Hi factorialmap, 

Thanks for this suggestion. 

If you're looking for a full copy of the data in Ergast, that's actually available to download from them in .csv or MySQL format, and that might serve you better than trying to recreate the database through our functions. Take a look here: http://ergast.com/mrd/db/. Note that in the future Ergast will be deprecated and not updated past 2024. We have leads on alternate data sources but they may use a different database schema and primary keys. As such, I think we'd likely prefer not to start providing that information currently, in expectation that it changes in less than a year.

There's some additional information that our package doesn't return to the users from Ergast, so this would avoid dropping those (and all of the Id columns) from all of the tables.

I've done some (other) work from the .csv files and found them easy to work with.

**Comment by factorialmap** [comment]
it works. Thank you so much for that
