### ISSUE TITLE
Session Sprint Qualification can not be retrieved

### ISSUE THREAD

**Issue by appiehappie999** [SCasanova/f1dataR#253]
Module: load_race_session does not allow to retrieve 'SQ' data to be retrieved. Python library fastf1 3.5.5 does allow this to be retrieved. Verified by python code.

Also I had trouble with the following code:
session <- load_race_session(2024,5,'R') I got constantly an error message "season must be 'current' or between 2018 and 2024. However 'current' did not work either. 

It works only if you'll use:
session <- load_race_session(season=2024,5,'R')

Regards
Ab

**Comment by pbulsink** [comment]
Hi @appiehappie999, I'll take a look at the SQ data.

I think there's a (legacy) code quirk that you're running into with load_race_session(). If you check the docs, you'll find it has the following usage:

```r
load_race_session(
  obj_name = "session",
  season = get_current_season(),
  round = 1,
  session = "R",
  log_level = "WARNING",
  race = lifecycle::deprecated()
)
```
So, technically you're putting in `load_race_session(obj_name = 2024, season = 5, round = 'R')`...

It's a discussion for us to have about if we want to reorganize the argument order on that function but *technically* it works as it's supposed to. Thanks for highlighting the difference in what the expected use case would be vs the actual patterns required.
