### ISSUE TITLE
FastF1 plotting update

### ISSUE THREAD

**Issue by pbulsink** [SCasanova/f1dataR#259]
There's a major update to plotting in FastF1 that we can likely mirror to API calls.

See https://github.com/theOehrly/Fast-F1/releases/tag/v3.4.0

I think in particular the Driver-Team colour coordination is beneficial to our users.

**Comment by pbulsink** [comment]
Might also have to shut down the python@3.8 test check

**Comment by SCasanova** [comment]
Awesome! I'm currently on holiday bu I will take a look as soon as I arrive home

**Comment by pbulsink** [comment]
> Awesome! I'm currently on holiday bu I will take a look as soon as I arrive home

No rush! I'm working on testing changes so will shut down the python@3.8, the enhancements part of this can happen as it happens.

**Comment by pbulsink** [comment]
I think I'll have a look at this over the next few days.

**Comment by pbulsink** [comment]
Closed with #264 #265
