### ISSUE TITLE
Make constructorId available somewhere (either via load_results or joined in load_drivers?)

### ISSUE THREAD

**Issue by christianlohr9** [SCasanova/f1dataR#3]
Maybe you already have the constructorId somewhere in a function, but either I'm too blind or that isn't the case ;)

It'd be awesome to have the Constructor list matched to drivers...
I'm wondering if the easiest way is to get both lists via `load_results()` instead of scraping the `https://ergast.com/api/f1/2022/constructors.json` (because via URL there's no driver ID to match...

Thx & regards
Christian

**Comment by SCasanova** [comment]
Hi Christian. There is a data frame that includes driver and constructor data loaded into the package. Not a function per se but that might solve it. 

If you're referencing something else do let me know tho.

**Comment by christianlohr9** [comment]
Oh... Completely missed out on that one.

Great work!
Thx and sorry 😬

**Comment by christianlohr9** [comment]
I'm blind.

**Comment by christianlohr9** [comment]
Please change `Sergio P_rez` to `Sergio Perez`.

Dunno if it's necessary to reopen issues for something like that.
Just let me know if it bothers you ;)

**Comment by SCasanova** [comment]
No bother at all. I do think a different issue altogether could be better. 

I will do that. It must be an encoding issue because of the accent on the e
