### ISSUE TITLE
driver_constructor_data for past seasons

### ISSUE THREAD

**Issue by christianlohr9** [SCasanova/f1dataR#37]
Hi,

either I'm blind again or this dataframe only works for current drivers.
Is it possible to create a df for past seasons?

Imo a static df would be ok for this and I'd love to help / provide the df for past seasons.

Best regards,
Christian

**Comment by pbulsink** [comment]
I think it already is a static df in the package - certainly I'd suggest submitting a pull request to update to 2023 driver/constructors. 

Some challenge appears though for past seasons where a driver may have driven for more than one team (think Russell in 2020 when he subbed for Mercedes in Bahrain). The best solution in general might be for `load_results()` (and other functions) return both driver **and** constructor id?

**Comment by pbulsink** [comment]
Now when you get the results from `load_results()` it includes the constructorId of each driver. That's the most reliable way to identify the driver/constructor pairing and doesn't need manual updating each season. We should likely modify the data frame in the package to take the drivers out and have it essentially be just a colour reference for the constructors.

**Comment by pbulsink** [comment]
> Now when you get the results from `load_results()` it includes the constructorId of each driver. That's the most reliable way to identify the driver/constructor pairing and doesn't need manual updating each season. We should likely modify the data frame in the package to take the drivers out and have it essentially be just a colour reference for the constructors.

Note: this is still missing for sprint races - I'll have to look into them to see if Ergast passes that data or not for us to include.

**Comment by pbulsink** [comment]
From now, my likely only suggestion would be a table of constructor_id and their team colours for plotting purposes.

**Comment by pbulsink** [comment]
Close once #83 merges?

This results in having only constructor_data available - driver data can be collected in part by `load_drivers()` (i.e. their wikipedia url, full name, etc) and, most crucially, the driver-constructor relationship is maintained for all race and sprint results.

I'd suggest that if you're working on practices/qualis you refer to the driver/constructor relationship from the associated race, and interpolate (if possible) if there are any substitute/junior/test drivers doing the practice session.

**Comment by SCasanova** [comment]
Closed by #83 (available by joining constructors and drivers)
