### ISSUE TITLE
## [Codecov] Report

### ISSUE THREAD

**Issue by pbulsink** [SCasanova/f1dataR#42]
As per below suggestion from #41, suggest integrating codecov for test coverage purposes.

             ## [Codecov](https://app.codecov.io/gh/SCasanova/f1dataR/pull/41?src=pr&el=h1&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=None) Report
> :exclamation: No coverage uploaded for pull request base (`master@08a12a2`). [Click here to learn what that means](https://docs.codecov.io/docs/error-reference?utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=None#section-missing-base-commit).
> The diff coverage is `n/a`.

> :exclamation: Current head 4671abd differs from pull request most recent head 01965e4. Consider uploading reports for the commit 01965e4 to get more accurate results

:mega: This organization is not using Codecov’s [GitHub App Integration](https://github.com/apps/codecov). We recommend you install it so Codecov can continue to function properly for your repositories. [Learn more](https://about.codecov.io/blog/codecov-is-updating-its-github-integration/?utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=None)

```diff
@@            Coverage Diff            @@
##             master      #41   +/-   ##
=========================================
  Coverage          ?   93.54%           
=========================================
  Files             ?       16           
  Lines             ?      341           
  Branches          ?        0           
=========================================
  Hits              ?      319           
  Misses            ?       22           
  Partials          ?        0           
```

_Originally posted by @codecov-commenter in https://github.com/SCasanova/f1dataR/issues/41#issuecomment-1535540702_

**Comment by pbulsink** [comment]
Could also put a codecov badge on the main page.

**Comment by SCasanova** [comment]
I'm a little unclear on what we need to do here specifically

**Comment by pbulsink** [comment]
I think just 'installing' codecov to your github profile and enabling it for this repo would end the warning that appears after the 📣 symbol. If you click the link under Github App Integeration it should guide you through that install. 

It's a change in authorization protocol for codecov that will soon end the OAuth connection and rely on a more native github integration.

**Comment by SCasanova** [comment]
Perfect thanks. This should be fixed now then!
