### ISSUE TITLE
[ENH] Ergast Use HTTP/HTTPS & connection settings

### ISSUE THREAD

**Issue by pbulsink** [SCasanova/f1dataR#52]
With Ergast down over the past few days I've been digging around. I think usually the code uses http: connections to Ergast, but this should likely be changed to https: to protect our users. Likewise, we should centralize assignment of the url (i.e. http[s]://ergast.com/api/f1) to make it easy to try a fall back to http: if https: is down (as was the case earlier this week).

**Comment by pbulsink** [comment]
I can tackle this at some point in the coming weeks.

**Comment by SCasanova** [comment]
Good catch, thank you for that

**Comment by SCasanova** [comment]
Closed by #57
