### ISSUE TITLE
Missing Time variable

### ISSUE THREAD

**Issue by SCasanova** [SCasanova/f1dataR#71]
I don't know if this is a problem on my machine but it seems that time variables are all NA for telemetry data

**Comment by pbulsink** [comment]
I've run into this too - I thought I captured it all in the processing of the results from get_telemetry and get_laps but maybe not?

Can you confirm what your python and fastf1 version is?

**Comment by SCasanova** [comment]
I'm on Python 3.10.8 and fastf1 3.0.4

**Comment by pbulsink** [comment]
Got it. I solved this in the `load_session_laps()` but didn't realize it appeared in here too. I can update the code and tests to capture should this pop up in the future, but give a few days...

From load_session_laps.R(line 50ish):

The FF1 function returns timedelta64 results for the below columns, which don't properly convert to R compatible types. Instead, use the dt.total_seconds() function inherent to the type to convert in Python before extracting the DataFrame to the R data.frame

**Comment by pbulsink** [comment]
Do you want me to investigate the failure on vignette for old ff1 versions shown in the build failure for #84 ?

**Comment by SCasanova** [comment]
If you have the time that would be great yes thanks

**Comment by SCasanova** [comment]
Closed by #84
