### ISSUE TITLE
Force fixed aspect ratio in plot_fastest?

### ISSUE THREAD

**Issue by pbulsink** [SCasanova/f1dataR#89]
I noticed that the aspect ratio for plots are not fixed, this makes some tracks look really weird: 
![image](https://github.com/SCasanova/f1dataR/assets/5419974/72dc094f-5a28-4b93-9e79-7bc3ad8b0431)

I tried to use `ggplot2::coord_fixed()` but that messes with the rest of the plotting properties, and looks bad with white bars on the plot edges and text not showing up right:
![image](https://github.com/SCasanova/f1dataR/assets/5419974/c4657ef6-96d5-403d-ad8b-bb452a763e1e)

I'm not a great ggplot user, so my fixes would be very clumsy. See some suggestions at https://stackoverflow.com/questions/23349181/how-to-color-entire-background-in-ggplot2-when-using-coord-fixed

**Comment by pbulsink** [comment]
Closed by #102

**Comment by pbulsink** [comment]
@SCasanova I have a new mechanism to force the unit equivalence and centre the plots, but it leaves each plot as a square. If the user has a non-square plotting window, do you want to leave the border square (to show them howto crop it if they want) or drop the border completely?

![image](https://github.com/SCasanova/f1dataR/assets/5419974/45e2f6fe-2be3-49c3-afa6-9735bf473692)

Once done, I'll integrate this to the vignettes rebuild and improve their quality per #175

**Comment by SCasanova** [comment]
Hmm but are the coordinates accurate? If so then I'm ok with the square
