### ISSUE TITLE
Examples should be added to the functions

### ISSUE THREAD

**Issue by pbulsink** [SCasanova/f1dataR#95]
Perhaps examples should be added to the functions as well but this can also be done after the 1.0.0 move

_Originally posted by @SCasanova in https://github.com/SCasanova/f1dataR/issues/59#issuecomment-1597800711_

(Make a new/separate issue to track contributions)

**Comment by pbulsink** [comment]
Started working on this see pbulsink/f1dataR docs branch - PR to come when done.

**Comment by SCasanova** [comment]
Closed by #98
