### ISSUE TITLE
Clarify License

### ISSUE THREAD

**Issue by pbulsink** [SCasanova/f1dataR#97]
Currently project has a barebones license statement. Should clarify to a common Open Source license (MIT/GPL etc.)

**Comment by pbulsink** [comment]
As per https://r-pkgs.org/license.html non-sharable licenses can't be processed by CRAN. 

Note too FastF1 uses MIT license.

**Comment by SCasanova** [comment]
Good point. I have a train ride tomorrow morning where I can dive into it

**Comment by SCasanova** [comment]
Closed by #101
